version: 0.2
env:
  variables:
    ECR_REPO: 985991030409.dkr.ecr.us-east-1.amazonaws.com/momos-backend
phases:
  build:
    commands:
      - echo "Building a Docker image.."
      - docker build -t momos-backend . --file Dockerfile
      - echo "Tagging Docker image for ECR.."
      - echo $CODEBUILD_SOURCE_VERSION
      # - docker tag momos-backend ${ECR_REPO}:${CODEBUILD_SOURCE_VERSION}
      - docker tag momos-backend ${ECR_REPO}:lastest
      - echo "Logging into ECR.."
      - $(aws ecr get-login-password --region $AWS_DEFAULT_REGION --no-include-email)
      - echo "Pushing Docker image to ECR.."
      # - docker push ${ECR_REPO}:${CODEBUILD_SOURCE_VERSION}
      - docker push ${ECR_REPO}:lastest